# This is the config file for the Simple Forms extension.

#stylesheet: assets/simpleforms.css
#template: assets/simpleforms_form.twig
template: form/_contact-form.html.twig
mail_template: assets/simpleforms_mail.twig
message_ok: Thanks! Your message has been sent.
message_error: There was an error in the form. Please check the form, and try again.
message_technical: There were some technical difficulties, so your message was not sent. We apologize for the inconvenience.
button_text: Send
# Optional. Used only, when you have a file field.
# mime_types_message: "Not allowed file type. Allowed file types are:"

# ReCaptcha Config - Set these options to enable ReCaptcha spam protection.
# Generate your keys at https://www.google.com/recaptcha/admin/create
recaptcha_enabled: false
recaptcha_public_key: ''
recaptcha_private_key: ''
recaptcha_error_message: "The CAPTCHA wasn't entered correctly. Please try again."
recaptcha_theme: clean

# Enable CSRF protection for forms. You should leave this set to 'true', unless
# you know what you're doing.
csrf: true

# Default fallback sender email
# this is required because Swiftmailer will reject the message without one
# please make this a sensible existing email address
from_email: ****@*********.com
from_name: Contact Form

# global cc email address
# set this value to an email address that will receive a copy of every email from simpleforms
# recipient_cc_email: info@example.com
# recipient_cc_name: Info

# global bcc email address
# set this value to an email address that will receive a blind copy of every email from simpleforms
# recipient_bcc_email: info@example.com

# global testmode
# for development all email will be sent to this address
# all other recipient and cc addresses will be ignored
# remove or set 'testmode' to false for a production site
#testmode : false
testmode_recipient: ****@*********.com

# from_email and from_name can be set for picky SMTP servers

# A simple contact form. Use as {{ simpleform('contact') }} in your templates.
contact:
  mail_subject: More Information Requested
  recipient_email: ****@*********.com
  recipient_name: cory
  fields:
    name:
      type: text
      placeholder: Bruce Wayne
      required: true
    email:
      type: email
      label: Email address
      placeholder: Bruce@WayneEnterprises.com
      required: true
    message:
      type: textarea
      placeholder: Your message ..
      maxlength: 250
      required: true
